// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.61.1.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'out_of_band_receiver_generated.io.dart'
    if (dart.library.html) 'out_of_band_receiver_generated.web.dart';

abstract class OutOfBandReceiverFFI {
  Future<int> outOfBandReceiverConnectionExists(
      {required int handle, required Uint32List connHandles, dynamic hint});

  FlutterRustBridgeTaskConstMeta
      get kOutOfBandReceiverConnectionExistsConstMeta;

  Future<String> outOfBandReceiverBuildConnection(
      {required int handle, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kOutOfBandReceiverBuildConnectionConstMeta;

  Future<String> outOfBandReceiverGetThreadId(
      {required int handle, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kOutOfBandReceiverGetThreadIdConstMeta;

  Future<String> outOfBandReceiverSerialize(
      {required int handle, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kOutOfBandReceiverSerializeConstMeta;

  Future<int> outOfBandReceiverDeserialize(
      {required String oobData, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kOutOfBandReceiverDeserializeConstMeta;

  Future<void> outOfBandReceiverRelease({required int handle, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kOutOfBandReceiverReleaseConstMeta;
}

class OutOfBandReceiverFFIImpl implements OutOfBandReceiverFFI {
  final OutOfBandReceiverFFIPlatform _platform;
  factory OutOfBandReceiverFFIImpl(ExternalLibrary dylib) =>
      OutOfBandReceiverFFIImpl.raw(OutOfBandReceiverFFIPlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory OutOfBandReceiverFFIImpl.wasm(FutureOr<WasmModule> module) =>
      OutOfBandReceiverFFIImpl(module as ExternalLibrary);
  OutOfBandReceiverFFIImpl.raw(this._platform);
  Future<int> outOfBandReceiverConnectionExists(
      {required int handle, required Uint32List connHandles, dynamic hint}) {
    var arg0 = api2wire_u32(handle);
    var arg1 = _platform.api2wire_uint_32_list(connHandles);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner
          .wire_out_of_band_receiver_connection_exists(port_, arg0, arg1),
      parseSuccessData: _wire2api_u32,
      constMeta: kOutOfBandReceiverConnectionExistsConstMeta,
      argValues: [handle, connHandles],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta
      get kOutOfBandReceiverConnectionExistsConstMeta =>
          const FlutterRustBridgeTaskConstMeta(
            debugName: "out_of_band_receiver_connection_exists",
            argNames: ["handle", "connHandles"],
          );

  Future<String> outOfBandReceiverBuildConnection(
      {required int handle, dynamic hint}) {
    var arg0 = api2wire_u32(handle);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner
          .wire_out_of_band_receiver_build_connection(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kOutOfBandReceiverBuildConnectionConstMeta,
      argValues: [handle],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta
      get kOutOfBandReceiverBuildConnectionConstMeta =>
          const FlutterRustBridgeTaskConstMeta(
            debugName: "out_of_band_receiver_build_connection",
            argNames: ["handle"],
          );

  Future<String> outOfBandReceiverGetThreadId(
      {required int handle, dynamic hint}) {
    var arg0 = api2wire_u32(handle);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_out_of_band_receiver_get_thread_id(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kOutOfBandReceiverGetThreadIdConstMeta,
      argValues: [handle],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kOutOfBandReceiverGetThreadIdConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "out_of_band_receiver_get_thread_id",
        argNames: ["handle"],
      );

  Future<String> outOfBandReceiverSerialize(
      {required int handle, dynamic hint}) {
    var arg0 = api2wire_u32(handle);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_out_of_band_receiver_serialize(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kOutOfBandReceiverSerializeConstMeta,
      argValues: [handle],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kOutOfBandReceiverSerializeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "out_of_band_receiver_serialize",
        argNames: ["handle"],
      );

  Future<int> outOfBandReceiverDeserialize(
      {required String oobData, dynamic hint}) {
    var arg0 = _platform.api2wire_String(oobData);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_out_of_band_receiver_deserialize(port_, arg0),
      parseSuccessData: _wire2api_u32,
      constMeta: kOutOfBandReceiverDeserializeConstMeta,
      argValues: [oobData],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kOutOfBandReceiverDeserializeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "out_of_band_receiver_deserialize",
        argNames: ["oobData"],
      );

  Future<void> outOfBandReceiverRelease({required int handle, dynamic hint}) {
    var arg0 = api2wire_u32(handle);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_out_of_band_receiver_release(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kOutOfBandReceiverReleaseConstMeta,
      argValues: [handle],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kOutOfBandReceiverReleaseConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "out_of_band_receiver_release",
        argNames: ["handle"],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  int _wire2api_u32(dynamic raw) {
    return raw as int;
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }

  void _wire2api_unit(dynamic raw) {
    return;
  }
}

// Section: api2wire

@protected
int api2wire_u32(int raw) {
  return raw;
}

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: finalizer
