// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.61.1.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'out_of_band_receiver_generated.dart';
export 'out_of_band_receiver_generated.dart';

class OutOfBandReceiverFFIPlatform
    extends FlutterRustBridgeBase<OutOfBandReceiverFFIWire>
    with FlutterRustBridgeSetupMixin {
  OutOfBandReceiverFFIPlatform(FutureOr<WasmModule> dylib)
      : super(OutOfBandReceiverFFIWire(dylib)) {
    setupMixinConstructor();
  }
  Future<void> setup() => inner.init;

// Section: api2wire

  @protected
  String api2wire_String(String raw) {
    return raw;
  }

  @protected
  Uint32List api2wire_uint_32_list(Uint32List raw) {
    return raw;
  }

  @protected
  Uint8List api2wire_uint_8_list(Uint8List raw) {
    return raw;
  }
// Section: finalizer

}

// Section: WASM wire module

@JS('wasm_bindgen')
external OutOfBandReceiverFFIWasmModule get wasmModule;

@JS()
@anonymous
class OutOfBandReceiverFFIWasmModule implements WasmModule {
  external Object /* Promise */ call([String? moduleName]);
  external OutOfBandReceiverFFIWasmModule bind(
      dynamic thisArg, String moduleName);
  external dynamic /* void */ wire_out_of_band_receiver_connection_exists(
      NativePortType port_, int handle, Uint32List conn_handles);

  external dynamic /* void */ wire_out_of_band_receiver_build_connection(
      NativePortType port_, int handle);

  external dynamic /* void */ wire_out_of_band_receiver_get_thread_id(
      NativePortType port_, int handle);

  external dynamic /* void */ wire_out_of_band_receiver_serialize(
      NativePortType port_, int handle);

  external dynamic /* void */ wire_out_of_band_receiver_deserialize(
      NativePortType port_, String oob_data);

  external dynamic /* void */ wire_out_of_band_receiver_release(
      NativePortType port_, int handle);
}

// Section: WASM wire connector

class OutOfBandReceiverFFIWire
    extends FlutterRustBridgeWasmWireBase<OutOfBandReceiverFFIWasmModule> {
  OutOfBandReceiverFFIWire(FutureOr<WasmModule> module)
      : super(WasmModule.cast<OutOfBandReceiverFFIWasmModule>(module));

  void wire_out_of_band_receiver_connection_exists(
          NativePortType port_, int handle, Uint32List conn_handles) =>
      wasmModule.wire_out_of_band_receiver_connection_exists(
          port_, handle, conn_handles);

  void wire_out_of_band_receiver_build_connection(
          NativePortType port_, int handle) =>
      wasmModule.wire_out_of_band_receiver_build_connection(port_, handle);

  void wire_out_of_band_receiver_get_thread_id(
          NativePortType port_, int handle) =>
      wasmModule.wire_out_of_band_receiver_get_thread_id(port_, handle);

  void wire_out_of_band_receiver_serialize(NativePortType port_, int handle) =>
      wasmModule.wire_out_of_band_receiver_serialize(port_, handle);

  void wire_out_of_band_receiver_deserialize(
          NativePortType port_, String oob_data) =>
      wasmModule.wire_out_of_band_receiver_deserialize(port_, oob_data);

  void wire_out_of_band_receiver_release(NativePortType port_, int handle) =>
      wasmModule.wire_out_of_band_receiver_release(port_, handle);
}
