// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.61.1.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'out_of_band_sender_generated.io.dart'
    if (dart.library.html) 'out_of_band_sender_generated.web.dart';

abstract class OutOfBandSenderFFI {
  Future<int> outOfBandSenderCreate({required String config, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kOutOfBandSenderCreateConstMeta;

  Future<void> outOfBandSenderAppendMessage(
      {required int handle, required String msg, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kOutOfBandSenderAppendMessageConstMeta;

  Future<void> outOfBandSenderAppendService(
      {required int handle, required String service, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kOutOfBandSenderAppendServiceConstMeta;

  Future<void> outOfBandSenderAppendServiceDid(
      {required int handle, required String did, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kOutOfBandSenderAppendServiceDidConstMeta;

  Future<String> outOfBandSenderToMessage({required int handle, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kOutOfBandSenderToMessageConstMeta;

  Future<String> outOfBandSenderGetThreadId(
      {required int handle, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kOutOfBandSenderGetThreadIdConstMeta;

  Future<String> outOfBandSenderSerialize({required int handle, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kOutOfBandSenderSerializeConstMeta;

  Future<int> outOfBandSenderDeserialize(
      {required String oobData, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kOutOfBandSenderDeserializeConstMeta;

  Future<void> outOfBandSenderRelease({required int handle, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kOutOfBandSenderReleaseConstMeta;
}

class OutOfBandSenderFFIImpl implements OutOfBandSenderFFI {
  final OutOfBandSenderFFIPlatform _platform;
  factory OutOfBandSenderFFIImpl(ExternalLibrary dylib) =>
      OutOfBandSenderFFIImpl.raw(OutOfBandSenderFFIPlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory OutOfBandSenderFFIImpl.wasm(FutureOr<WasmModule> module) =>
      OutOfBandSenderFFIImpl(module as ExternalLibrary);
  OutOfBandSenderFFIImpl.raw(this._platform);
  Future<int> outOfBandSenderCreate({required String config, dynamic hint}) {
    var arg0 = _platform.api2wire_String(config);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_out_of_band_sender_create(port_, arg0),
      parseSuccessData: _wire2api_u32,
      constMeta: kOutOfBandSenderCreateConstMeta,
      argValues: [config],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kOutOfBandSenderCreateConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "out_of_band_sender_create",
        argNames: ["config"],
      );

  Future<void> outOfBandSenderAppendMessage(
      {required int handle, required String msg, dynamic hint}) {
    var arg0 = api2wire_u32(handle);
    var arg1 = _platform.api2wire_String(msg);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner
          .wire_out_of_band_sender_append_message(port_, arg0, arg1),
      parseSuccessData: _wire2api_unit,
      constMeta: kOutOfBandSenderAppendMessageConstMeta,
      argValues: [handle, msg],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kOutOfBandSenderAppendMessageConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "out_of_band_sender_append_message",
        argNames: ["handle", "msg"],
      );

  Future<void> outOfBandSenderAppendService(
      {required int handle, required String service, dynamic hint}) {
    var arg0 = api2wire_u32(handle);
    var arg1 = _platform.api2wire_String(service);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner
          .wire_out_of_band_sender_append_service(port_, arg0, arg1),
      parseSuccessData: _wire2api_unit,
      constMeta: kOutOfBandSenderAppendServiceConstMeta,
      argValues: [handle, service],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kOutOfBandSenderAppendServiceConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "out_of_band_sender_append_service",
        argNames: ["handle", "service"],
      );

  Future<void> outOfBandSenderAppendServiceDid(
      {required int handle, required String did, dynamic hint}) {
    var arg0 = api2wire_u32(handle);
    var arg1 = _platform.api2wire_String(did);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner
          .wire_out_of_band_sender_append_service_did(port_, arg0, arg1),
      parseSuccessData: _wire2api_unit,
      constMeta: kOutOfBandSenderAppendServiceDidConstMeta,
      argValues: [handle, did],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta
      get kOutOfBandSenderAppendServiceDidConstMeta =>
          const FlutterRustBridgeTaskConstMeta(
            debugName: "out_of_band_sender_append_service_did",
            argNames: ["handle", "did"],
          );

  Future<String> outOfBandSenderToMessage({required int handle, dynamic hint}) {
    var arg0 = api2wire_u32(handle);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_out_of_band_sender_to_message(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kOutOfBandSenderToMessageConstMeta,
      argValues: [handle],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kOutOfBandSenderToMessageConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "out_of_band_sender_to_message",
        argNames: ["handle"],
      );

  Future<String> outOfBandSenderGetThreadId(
      {required int handle, dynamic hint}) {
    var arg0 = api2wire_u32(handle);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_out_of_band_sender_get_thread_id(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kOutOfBandSenderGetThreadIdConstMeta,
      argValues: [handle],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kOutOfBandSenderGetThreadIdConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "out_of_band_sender_get_thread_id",
        argNames: ["handle"],
      );

  Future<String> outOfBandSenderSerialize({required int handle, dynamic hint}) {
    var arg0 = api2wire_u32(handle);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_out_of_band_sender_serialize(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kOutOfBandSenderSerializeConstMeta,
      argValues: [handle],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kOutOfBandSenderSerializeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "out_of_band_sender_serialize",
        argNames: ["handle"],
      );

  Future<int> outOfBandSenderDeserialize(
      {required String oobData, dynamic hint}) {
    var arg0 = _platform.api2wire_String(oobData);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_out_of_band_sender_deserialize(port_, arg0),
      parseSuccessData: _wire2api_u32,
      constMeta: kOutOfBandSenderDeserializeConstMeta,
      argValues: [oobData],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kOutOfBandSenderDeserializeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "out_of_band_sender_deserialize",
        argNames: ["oobData"],
      );

  Future<void> outOfBandSenderRelease({required int handle, dynamic hint}) {
    var arg0 = api2wire_u32(handle);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_out_of_band_sender_release(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kOutOfBandSenderReleaseConstMeta,
      argValues: [handle],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kOutOfBandSenderReleaseConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "out_of_band_sender_release",
        argNames: ["handle"],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  int _wire2api_u32(dynamic raw) {
    return raw as int;
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }

  void _wire2api_unit(dynamic raw) {
    return;
  }
}

// Section: api2wire

@protected
int api2wire_u32(int raw) {
  return raw;
}

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: finalizer
