version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: pub
    directory: "/packages/aries_vcx"
    versioning-strategy: increase # https://github.com/dependabot/dependabot-core/issues/6446
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/aries_vcx/example"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_aries_vcx"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_aries_vcx/example"
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: "/packages/aries_vcx/native"
    schedule:
      interval: weekly
