// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.61.1.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'logging_generated.io.dart'
    if (dart.library.html) 'logging_generated.web.dart';

abstract class Logging {
  Future<void> initDefaultLogger({String? pattern, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kInitDefaultLoggerConstMeta;
}

class LoggingImpl implements Logging {
  final LoggingPlatform _platform;
  factory LoggingImpl(ExternalLibrary dylib) =>
      LoggingImpl.raw(LoggingPlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory LoggingImpl.wasm(FutureOr<WasmModule> module) =>
      LoggingImpl(module as ExternalLibrary);
  LoggingImpl.raw(this._platform);
  Future<void> initDefaultLogger({String? pattern, dynamic hint}) {
    var arg0 = _platform.api2wire_opt_String(pattern);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_init_default_logger(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kInitDefaultLoggerConstMeta,
      argValues: [pattern],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kInitDefaultLoggerConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "init_default_logger",
        argNames: ["pattern"],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  void _wire2api_unit(dynamic raw) {
    return;
  }
}

// Section: api2wire

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: finalizer
