// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.61.1.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'testing_generated.io.dart'
    if (dart.library.html) 'testing_generated.web.dart';

abstract class Testing {
  Future<void> enableMocks({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kEnableMocksConstMeta;
}

class TestingImpl implements Testing {
  final TestingPlatform _platform;
  factory TestingImpl(ExternalLibrary dylib) =>
      TestingImpl.raw(TestingPlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory TestingImpl.wasm(FutureOr<WasmModule> module) =>
      TestingImpl(module as ExternalLibrary);
  TestingImpl.raw(this._platform);
  Future<void> enableMocks({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_enable_mocks(port_),
      parseSuccessData: _wire2api_unit,
      constMeta: kEnableMocksConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kEnableMocksConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "enable_mocks",
        argNames: [],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  void _wire2api_unit(dynamic raw) {
    return;
  }
}

// Section: api2wire

// Section: finalizer
