// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.67.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'utils_generated.io.dart'
    if (dart.library.html) 'utils_generated.web.dart';

abstract class Utils {
  Future<void> shutdown({bool? deleteAll, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kShutdownConstMeta;

  Future<String> getVersion({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGetVersionConstMeta;
}

class UtilsImpl implements Utils {
  final UtilsPlatform _platform;
  factory UtilsImpl(ExternalLibrary dylib) =>
      UtilsImpl.raw(UtilsPlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory UtilsImpl.wasm(FutureOr<WasmModule> module) =>
      UtilsImpl(module as ExternalLibrary);
  UtilsImpl.raw(this._platform);
  Future<void> shutdown({bool? deleteAll, dynamic hint}) {
    var arg0 = _platform.api2wire_opt_box_autoadd_bool(deleteAll);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_shutdown(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kShutdownConstMeta,
      argValues: [deleteAll],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kShutdownConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "shutdown",
        argNames: ["deleteAll"],
      );

  Future<String> getVersion({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_get_version(port_),
      parseSuccessData: _wire2api_String,
      constMeta: kGetVersionConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kGetVersionConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "get_version",
        argNames: [],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }

  void _wire2api_unit(dynamic raw) {
    return;
  }
}

// Section: api2wire

@protected
bool api2wire_bool(bool raw) {
  return raw;
}

// Section: finalizer
