[package]
name = "aries_vcx"
version = "0.0.0"
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.68.*"
heck = "0.4.0"

[dependencies]
flutter_rust_bridge = "1.67.*"
libvcx_core = { git="https://github.com/hyperledger/aries-vcx", branch="main", default-features = false }
futures = "0.3"
anyhow = "1.0.*"
tokio = { version = "1.14.0", features = ["rt", "macros"] }
openssl = { version = "0.10", features = ["vendored"] }
