#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.61.1.

use crate::issuer_credential::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

// Section: wire functions

fn wire_issuer_credential_deserialize_impl(
    port_: MessagePort,
    credential_data: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "issuer_credential_deserialize",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_credential_data = credential_data.wire2api();
            move |task_callback| issuer_credential_deserialize(api_credential_data)
        },
    )
}
fn wire_issuer_credential_serialize_impl(
    port_: MessagePort,
    handle_credential: impl Wire2Api<u32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "issuer_credential_serialize",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_handle_credential = handle_credential.wire2api();
            move |task_callback| issuer_credential_serialize(api_handle_credential)
        },
    )
}
fn wire_issuer_credential_update_state_v2_impl(
    port_: MessagePort,
    handle_credential: impl Wire2Api<u32> + UnwindSafe,
    connection_handle: impl Wire2Api<u32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "issuer_credential_update_state_v2",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_handle_credential = handle_credential.wire2api();
            let api_connection_handle = connection_handle.wire2api();
            move |task_callback| {
                issuer_credential_update_state_v2(api_handle_credential, api_connection_handle)
            }
        },
    )
}
fn wire_issuer_credential_update_state_with_message_v2_impl(
    port_: MessagePort,
    handle_credential: impl Wire2Api<u32> + UnwindSafe,
    connection_handle: impl Wire2Api<u32> + UnwindSafe,
    message: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "issuer_credential_update_state_with_message_v2",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_handle_credential = handle_credential.wire2api();
            let api_connection_handle = connection_handle.wire2api();
            let api_message = message.wire2api();
            move |task_callback| {
                issuer_credential_update_state_with_message_v2(
                    api_handle_credential,
                    api_connection_handle,
                    api_message,
                )
            }
        },
    )
}
fn wire_issuer_credential_get_state_impl(
    port_: MessagePort,
    handle_credential: impl Wire2Api<u32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "issuer_credential_get_state",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_handle_credential = handle_credential.wire2api();
            move |task_callback| issuer_credential_get_state(api_handle_credential)
        },
    )
}
fn wire_issuer_credential_get_rev_reg_id_impl(
    port_: MessagePort,
    handle_credential: impl Wire2Api<u32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "issuer_credential_get_rev_reg_id",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_handle_credential = handle_credential.wire2api();
            move |task_callback| issuer_credential_get_rev_reg_id(api_handle_credential)
        },
    )
}
fn wire_issuer_credential_create_impl(
    port_: MessagePort,
    source_id: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "issuer_credential_create",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_source_id = source_id.wire2api();
            move |task_callback| issuer_credential_create(api_source_id)
        },
    )
}
fn wire_issuer_credential_revoke_local_impl(
    port_: MessagePort,
    handle_credential: impl Wire2Api<u32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "issuer_credential_revoke_local",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_handle_credential = handle_credential.wire2api();
            move |task_callback| issuer_credential_revoke_local(api_handle_credential)
        },
    )
}
fn wire_issuer_credential_is_revokable_impl(
    port_: MessagePort,
    handle_credential: impl Wire2Api<u32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "issuer_credential_is_revokable",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_handle_credential = handle_credential.wire2api();
            move |task_callback| issuer_credential_is_revokable(api_handle_credential)
        },
    )
}
fn wire_issuer_credential_send_credential_impl(
    port_: MessagePort,
    handle_credential: impl Wire2Api<u32> + UnwindSafe,
    handle_connection: impl Wire2Api<u32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "issuer_credential_send_credential",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_handle_credential = handle_credential.wire2api();
            let api_handle_connection = handle_connection.wire2api();
            move |task_callback| {
                issuer_credential_send_credential(api_handle_credential, api_handle_connection)
            }
        },
    )
}
fn wire_issuer_credential_send_offer_v2_impl(
    port_: MessagePort,
    handle_credential: impl Wire2Api<u32> + UnwindSafe,
    handle_connection: impl Wire2Api<u32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "issuer_credential_send_offer_v2",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_handle_credential = handle_credential.wire2api();
            let api_handle_connection = handle_connection.wire2api();
            move |task_callback| {
                issuer_credential_send_offer_v2(api_handle_credential, api_handle_connection)
            }
        },
    )
}
fn wire_issuer_credential_mark_offer_msg_sent_impl(
    port_: MessagePort,
    handle_credential: impl Wire2Api<u32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "issuer_credential_mark_offer_msg_sent",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_handle_credential = handle_credential.wire2api();
            move |task_callback| issuer_credential_mark_offer_msg_sent(api_handle_credential)
        },
    )
}
fn wire_issuer_credential_build_offer_msg_v2_impl(
    port_: MessagePort,
    credential_handle: impl Wire2Api<u32> + UnwindSafe,
    cred_def_handle: impl Wire2Api<u32> + UnwindSafe,
    rev_reg_handle: impl Wire2Api<u32> + UnwindSafe,
    credential_json: impl Wire2Api<String> + UnwindSafe,
    comment: impl Wire2Api<Option<String>> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "issuer_credential_build_offer_msg_v2",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_credential_handle = credential_handle.wire2api();
            let api_cred_def_handle = cred_def_handle.wire2api();
            let api_rev_reg_handle = rev_reg_handle.wire2api();
            let api_credential_json = credential_json.wire2api();
            let api_comment = comment.wire2api();
            move |task_callback| {
                issuer_credential_build_offer_msg_v2(
                    api_credential_handle,
                    api_cred_def_handle,
                    api_rev_reg_handle,
                    api_credential_json,
                    api_comment,
                )
            }
        },
    )
}
fn wire_issuer_credential_get_offer_msg_impl(
    port_: MessagePort,
    credential_handle: impl Wire2Api<u32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "issuer_credential_get_offer_msg",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_credential_handle = credential_handle.wire2api();
            move |task_callback| issuer_credential_get_offer_msg(api_credential_handle)
        },
    )
}
fn wire_issuer_credential_release_impl(
    port_: MessagePort,
    credential_handle: impl Wire2Api<u32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "issuer_credential_release",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_credential_handle = credential_handle.wire2api();
            move |task_callback| issuer_credential_release(api_credential_handle)
        },
    )
}
fn wire_issuer_credential_get_thread_id_impl(
    port_: MessagePort,
    credential_handle: impl Wire2Api<u32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "issuer_credential_get_thread_id",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_credential_handle = credential_handle.wire2api();
            move |task_callback| issuer_credential_get_thread_id(api_credential_handle)
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<u32> for u32 {
    fn wire2api(self) -> u32 {
        self
    }
}
impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

// Section: impl IntoDart

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    use super::*;
    // Section: wire functions

    #[wasm_bindgen]
    pub fn wire_issuer_credential_deserialize(port_: MessagePort, credential_data: String) {
        wire_issuer_credential_deserialize_impl(port_, credential_data)
    }

    #[wasm_bindgen]
    pub fn wire_issuer_credential_serialize(port_: MessagePort, handle_credential: u32) {
        wire_issuer_credential_serialize_impl(port_, handle_credential)
    }

    #[wasm_bindgen]
    pub fn wire_issuer_credential_update_state_v2(
        port_: MessagePort,
        handle_credential: u32,
        connection_handle: u32,
    ) {
        wire_issuer_credential_update_state_v2_impl(port_, handle_credential, connection_handle)
    }

    #[wasm_bindgen]
    pub fn wire_issuer_credential_update_state_with_message_v2(
        port_: MessagePort,
        handle_credential: u32,
        connection_handle: u32,
        message: String,
    ) {
        wire_issuer_credential_update_state_with_message_v2_impl(
            port_,
            handle_credential,
            connection_handle,
            message,
        )
    }

    #[wasm_bindgen]
    pub fn wire_issuer_credential_get_state(port_: MessagePort, handle_credential: u32) {
        wire_issuer_credential_get_state_impl(port_, handle_credential)
    }

    #[wasm_bindgen]
    pub fn wire_issuer_credential_get_rev_reg_id(port_: MessagePort, handle_credential: u32) {
        wire_issuer_credential_get_rev_reg_id_impl(port_, handle_credential)
    }

    #[wasm_bindgen]
    pub fn wire_issuer_credential_create(port_: MessagePort, source_id: String) {
        wire_issuer_credential_create_impl(port_, source_id)
    }

    #[wasm_bindgen]
    pub fn wire_issuer_credential_revoke_local(port_: MessagePort, handle_credential: u32) {
        wire_issuer_credential_revoke_local_impl(port_, handle_credential)
    }

    #[wasm_bindgen]
    pub fn wire_issuer_credential_is_revokable(port_: MessagePort, handle_credential: u32) {
        wire_issuer_credential_is_revokable_impl(port_, handle_credential)
    }

    #[wasm_bindgen]
    pub fn wire_issuer_credential_send_credential(
        port_: MessagePort,
        handle_credential: u32,
        handle_connection: u32,
    ) {
        wire_issuer_credential_send_credential_impl(port_, handle_credential, handle_connection)
    }

    #[wasm_bindgen]
    pub fn wire_issuer_credential_send_offer_v2(
        port_: MessagePort,
        handle_credential: u32,
        handle_connection: u32,
    ) {
        wire_issuer_credential_send_offer_v2_impl(port_, handle_credential, handle_connection)
    }

    #[wasm_bindgen]
    pub fn wire_issuer_credential_mark_offer_msg_sent(port_: MessagePort, handle_credential: u32) {
        wire_issuer_credential_mark_offer_msg_sent_impl(port_, handle_credential)
    }

    #[wasm_bindgen]
    pub fn wire_issuer_credential_build_offer_msg_v2(
        port_: MessagePort,
        credential_handle: u32,
        cred_def_handle: u32,
        rev_reg_handle: u32,
        credential_json: String,
        comment: Option<String>,
    ) {
        wire_issuer_credential_build_offer_msg_v2_impl(
            port_,
            credential_handle,
            cred_def_handle,
            rev_reg_handle,
            credential_json,
            comment,
        )
    }

    #[wasm_bindgen]
    pub fn wire_issuer_credential_get_offer_msg(port_: MessagePort, credential_handle: u32) {
        wire_issuer_credential_get_offer_msg_impl(port_, credential_handle)
    }

    #[wasm_bindgen]
    pub fn wire_issuer_credential_release(port_: MessagePort, credential_handle: u32) {
        wire_issuer_credential_release_impl(port_, credential_handle)
    }

    #[wasm_bindgen]
    pub fn wire_issuer_credential_get_thread_id(port_: MessagePort, credential_handle: u32) {
        wire_issuer_credential_get_thread_id_impl(port_, credential_handle)
    }

    // Section: allocate functions

    // Section: related functions

    // Section: impl Wire2Api

    impl Wire2Api<String> for String {
        fn wire2api(self) -> String {
            self
        }
    }
    impl Wire2Api<Option<String>> for Option<String> {
        fn wire2api(self) -> Option<String> {
            self.map(Wire2Api::wire2api)
        }
    }

    impl Wire2Api<Vec<u8>> for Box<[u8]> {
        fn wire2api(self) -> Vec<u8> {
            self.into_vec()
        }
    }
    // Section: impl Wire2Api for JsValue

    impl Wire2Api<String> for JsValue {
        fn wire2api(self) -> String {
            self.as_string().expect("non-UTF-8 string, or not a string")
        }
    }
    impl Wire2Api<Option<String>> for JsValue {
        fn wire2api(self) -> Option<String> {
            (!self.is_undefined() && !self.is_null()).then(|| self.wire2api())
        }
    }
    impl Wire2Api<u32> for JsValue {
        fn wire2api(self) -> u32 {
            self.unchecked_into_f64() as _
        }
    }
    impl Wire2Api<u8> for JsValue {
        fn wire2api(self) -> u8 {
            self.unchecked_into_f64() as _
        }
    }
    impl Wire2Api<Vec<u8>> for JsValue {
        fn wire2api(self) -> Vec<u8> {
            self.unchecked_into::<js_sys::Uint8Array>().to_vec().into()
        }
    }
}
#[cfg(target_family = "wasm")]
pub use web::*;

#[cfg(not(target_family = "wasm"))]
mod io {
    use super::*;
    // Section: wire functions

    #[no_mangle]
    pub extern "C" fn wire_issuer_credential_deserialize(
        port_: i64,
        credential_data: *mut wire_uint_8_list,
    ) {
        wire_issuer_credential_deserialize_impl(port_, credential_data)
    }

    #[no_mangle]
    pub extern "C" fn wire_issuer_credential_serialize(port_: i64, handle_credential: u32) {
        wire_issuer_credential_serialize_impl(port_, handle_credential)
    }

    #[no_mangle]
    pub extern "C" fn wire_issuer_credential_update_state_v2(
        port_: i64,
        handle_credential: u32,
        connection_handle: u32,
    ) {
        wire_issuer_credential_update_state_v2_impl(port_, handle_credential, connection_handle)
    }

    #[no_mangle]
    pub extern "C" fn wire_issuer_credential_update_state_with_message_v2(
        port_: i64,
        handle_credential: u32,
        connection_handle: u32,
        message: *mut wire_uint_8_list,
    ) {
        wire_issuer_credential_update_state_with_message_v2_impl(
            port_,
            handle_credential,
            connection_handle,
            message,
        )
    }

    #[no_mangle]
    pub extern "C" fn wire_issuer_credential_get_state(port_: i64, handle_credential: u32) {
        wire_issuer_credential_get_state_impl(port_, handle_credential)
    }

    #[no_mangle]
    pub extern "C" fn wire_issuer_credential_get_rev_reg_id(port_: i64, handle_credential: u32) {
        wire_issuer_credential_get_rev_reg_id_impl(port_, handle_credential)
    }

    #[no_mangle]
    pub extern "C" fn wire_issuer_credential_create(port_: i64, source_id: *mut wire_uint_8_list) {
        wire_issuer_credential_create_impl(port_, source_id)
    }

    #[no_mangle]
    pub extern "C" fn wire_issuer_credential_revoke_local(port_: i64, handle_credential: u32) {
        wire_issuer_credential_revoke_local_impl(port_, handle_credential)
    }

    #[no_mangle]
    pub extern "C" fn wire_issuer_credential_is_revokable(port_: i64, handle_credential: u32) {
        wire_issuer_credential_is_revokable_impl(port_, handle_credential)
    }

    #[no_mangle]
    pub extern "C" fn wire_issuer_credential_send_credential(
        port_: i64,
        handle_credential: u32,
        handle_connection: u32,
    ) {
        wire_issuer_credential_send_credential_impl(port_, handle_credential, handle_connection)
    }

    #[no_mangle]
    pub extern "C" fn wire_issuer_credential_send_offer_v2(
        port_: i64,
        handle_credential: u32,
        handle_connection: u32,
    ) {
        wire_issuer_credential_send_offer_v2_impl(port_, handle_credential, handle_connection)
    }

    #[no_mangle]
    pub extern "C" fn wire_issuer_credential_mark_offer_msg_sent(
        port_: i64,
        handle_credential: u32,
    ) {
        wire_issuer_credential_mark_offer_msg_sent_impl(port_, handle_credential)
    }

    #[no_mangle]
    pub extern "C" fn wire_issuer_credential_build_offer_msg_v2(
        port_: i64,
        credential_handle: u32,
        cred_def_handle: u32,
        rev_reg_handle: u32,
        credential_json: *mut wire_uint_8_list,
        comment: *mut wire_uint_8_list,
    ) {
        wire_issuer_credential_build_offer_msg_v2_impl(
            port_,
            credential_handle,
            cred_def_handle,
            rev_reg_handle,
            credential_json,
            comment,
        )
    }

    #[no_mangle]
    pub extern "C" fn wire_issuer_credential_get_offer_msg(port_: i64, credential_handle: u32) {
        wire_issuer_credential_get_offer_msg_impl(port_, credential_handle)
    }

    #[no_mangle]
    pub extern "C" fn wire_issuer_credential_release(port_: i64, credential_handle: u32) {
        wire_issuer_credential_release_impl(port_, credential_handle)
    }

    #[no_mangle]
    pub extern "C" fn wire_issuer_credential_get_thread_id(port_: i64, credential_handle: u32) {
        wire_issuer_credential_get_thread_id_impl(port_, credential_handle)
    }

    // Section: allocate functions

    #[no_mangle]
    pub extern "C" fn new_uint_8_list_4(len: i32) -> *mut wire_uint_8_list {
        let ans = wire_uint_8_list {
            ptr: support::new_leak_vec_ptr(Default::default(), len),
            len,
        };
        support::new_leak_box_ptr(ans)
    }

    // Section: related functions

    // Section: impl Wire2Api

    impl Wire2Api<String> for *mut wire_uint_8_list {
        fn wire2api(self) -> String {
            let vec: Vec<u8> = self.wire2api();
            String::from_utf8_lossy(&vec).into_owned()
        }
    }

    impl Wire2Api<Vec<u8>> for *mut wire_uint_8_list {
        fn wire2api(self) -> Vec<u8> {
            unsafe {
                let wrap = support::box_from_leak_ptr(self);
                support::vec_from_leak_ptr(wrap.ptr, wrap.len)
            }
        }
    }
    // Section: wire structs

    #[repr(C)]
    #[derive(Clone)]
    pub struct wire_uint_8_list {
        ptr: *mut u8,
        len: i32,
    }

    // Section: impl NewWithNullPtr

    pub trait NewWithNullPtr {
        fn new_with_null_ptr() -> Self;
    }

    impl<T> NewWithNullPtr for *mut T {
        fn new_with_null_ptr() -> Self {
            std::ptr::null_mut()
        }
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;
