#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.61.1.

use crate::out_of_band_sender::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

// Section: wire functions

fn wire_out_of_band_sender_create_impl(
    port_: MessagePort,
    config: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "out_of_band_sender_create",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_config = config.wire2api();
            move |task_callback| out_of_band_sender_create(api_config)
        },
    )
}
fn wire_out_of_band_sender_append_message_impl(
    port_: MessagePort,
    handle: impl Wire2Api<u32> + UnwindSafe,
    msg: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "out_of_band_sender_append_message",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_handle = handle.wire2api();
            let api_msg = msg.wire2api();
            move |task_callback| out_of_band_sender_append_message(api_handle, api_msg)
        },
    )
}
fn wire_out_of_band_sender_append_service_impl(
    port_: MessagePort,
    handle: impl Wire2Api<u32> + UnwindSafe,
    service: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "out_of_band_sender_append_service",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_handle = handle.wire2api();
            let api_service = service.wire2api();
            move |task_callback| out_of_band_sender_append_service(api_handle, api_service)
        },
    )
}
fn wire_out_of_band_sender_append_service_did_impl(
    port_: MessagePort,
    handle: impl Wire2Api<u32> + UnwindSafe,
    did: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "out_of_band_sender_append_service_did",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_handle = handle.wire2api();
            let api_did = did.wire2api();
            move |task_callback| out_of_band_sender_append_service_did(api_handle, api_did)
        },
    )
}
fn wire_out_of_band_sender_to_message_impl(
    port_: MessagePort,
    handle: impl Wire2Api<u32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "out_of_band_sender_to_message",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_handle = handle.wire2api();
            move |task_callback| out_of_band_sender_to_message(api_handle)
        },
    )
}
fn wire_out_of_band_sender_get_thread_id_impl(
    port_: MessagePort,
    handle: impl Wire2Api<u32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "out_of_band_sender_get_thread_id",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_handle = handle.wire2api();
            move |task_callback| out_of_band_sender_get_thread_id(api_handle)
        },
    )
}
fn wire_out_of_band_sender_serialize_impl(
    port_: MessagePort,
    handle: impl Wire2Api<u32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "out_of_band_sender_serialize",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_handle = handle.wire2api();
            move |task_callback| out_of_band_sender_serialize(api_handle)
        },
    )
}
fn wire_out_of_band_sender_deserialize_impl(
    port_: MessagePort,
    oob_data: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "out_of_band_sender_deserialize",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_oob_data = oob_data.wire2api();
            move |task_callback| out_of_band_sender_deserialize(api_oob_data)
        },
    )
}
fn wire_out_of_band_sender_release_impl(
    port_: MessagePort,
    handle: impl Wire2Api<u32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "out_of_band_sender_release",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_handle = handle.wire2api();
            move |task_callback| out_of_band_sender_release(api_handle)
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<u32> for u32 {
    fn wire2api(self) -> u32 {
        self
    }
}
impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

// Section: impl IntoDart

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    use super::*;
    // Section: wire functions

    #[wasm_bindgen]
    pub fn wire_out_of_band_sender_create(port_: MessagePort, config: String) {
        wire_out_of_band_sender_create_impl(port_, config)
    }

    #[wasm_bindgen]
    pub fn wire_out_of_band_sender_append_message(port_: MessagePort, handle: u32, msg: String) {
        wire_out_of_band_sender_append_message_impl(port_, handle, msg)
    }

    #[wasm_bindgen]
    pub fn wire_out_of_band_sender_append_service(
        port_: MessagePort,
        handle: u32,
        service: String,
    ) {
        wire_out_of_band_sender_append_service_impl(port_, handle, service)
    }

    #[wasm_bindgen]
    pub fn wire_out_of_band_sender_append_service_did(
        port_: MessagePort,
        handle: u32,
        did: String,
    ) {
        wire_out_of_band_sender_append_service_did_impl(port_, handle, did)
    }

    #[wasm_bindgen]
    pub fn wire_out_of_band_sender_to_message(port_: MessagePort, handle: u32) {
        wire_out_of_band_sender_to_message_impl(port_, handle)
    }

    #[wasm_bindgen]
    pub fn wire_out_of_band_sender_get_thread_id(port_: MessagePort, handle: u32) {
        wire_out_of_band_sender_get_thread_id_impl(port_, handle)
    }

    #[wasm_bindgen]
    pub fn wire_out_of_band_sender_serialize(port_: MessagePort, handle: u32) {
        wire_out_of_band_sender_serialize_impl(port_, handle)
    }

    #[wasm_bindgen]
    pub fn wire_out_of_band_sender_deserialize(port_: MessagePort, oob_data: String) {
        wire_out_of_band_sender_deserialize_impl(port_, oob_data)
    }

    #[wasm_bindgen]
    pub fn wire_out_of_band_sender_release(port_: MessagePort, handle: u32) {
        wire_out_of_band_sender_release_impl(port_, handle)
    }

    // Section: allocate functions

    // Section: related functions

    // Section: impl Wire2Api

    impl Wire2Api<String> for String {
        fn wire2api(self) -> String {
            self
        }
    }

    impl Wire2Api<Vec<u8>> for Box<[u8]> {
        fn wire2api(self) -> Vec<u8> {
            self.into_vec()
        }
    }
    // Section: impl Wire2Api for JsValue

    impl Wire2Api<String> for JsValue {
        fn wire2api(self) -> String {
            self.as_string().expect("non-UTF-8 string, or not a string")
        }
    }
    impl Wire2Api<u32> for JsValue {
        fn wire2api(self) -> u32 {
            self.unchecked_into_f64() as _
        }
    }
    impl Wire2Api<u8> for JsValue {
        fn wire2api(self) -> u8 {
            self.unchecked_into_f64() as _
        }
    }
    impl Wire2Api<Vec<u8>> for JsValue {
        fn wire2api(self) -> Vec<u8> {
            self.unchecked_into::<js_sys::Uint8Array>().to_vec().into()
        }
    }
}
#[cfg(target_family = "wasm")]
pub use web::*;

#[cfg(not(target_family = "wasm"))]
mod io {
    use super::*;
    // Section: wire functions

    #[no_mangle]
    pub extern "C" fn wire_out_of_band_sender_create(port_: i64, config: *mut wire_uint_8_list) {
        wire_out_of_band_sender_create_impl(port_, config)
    }

    #[no_mangle]
    pub extern "C" fn wire_out_of_band_sender_append_message(
        port_: i64,
        handle: u32,
        msg: *mut wire_uint_8_list,
    ) {
        wire_out_of_band_sender_append_message_impl(port_, handle, msg)
    }

    #[no_mangle]
    pub extern "C" fn wire_out_of_band_sender_append_service(
        port_: i64,
        handle: u32,
        service: *mut wire_uint_8_list,
    ) {
        wire_out_of_band_sender_append_service_impl(port_, handle, service)
    }

    #[no_mangle]
    pub extern "C" fn wire_out_of_band_sender_append_service_did(
        port_: i64,
        handle: u32,
        did: *mut wire_uint_8_list,
    ) {
        wire_out_of_band_sender_append_service_did_impl(port_, handle, did)
    }

    #[no_mangle]
    pub extern "C" fn wire_out_of_band_sender_to_message(port_: i64, handle: u32) {
        wire_out_of_band_sender_to_message_impl(port_, handle)
    }

    #[no_mangle]
    pub extern "C" fn wire_out_of_band_sender_get_thread_id(port_: i64, handle: u32) {
        wire_out_of_band_sender_get_thread_id_impl(port_, handle)
    }

    #[no_mangle]
    pub extern "C" fn wire_out_of_band_sender_serialize(port_: i64, handle: u32) {
        wire_out_of_band_sender_serialize_impl(port_, handle)
    }

    #[no_mangle]
    pub extern "C" fn wire_out_of_band_sender_deserialize(
        port_: i64,
        oob_data: *mut wire_uint_8_list,
    ) {
        wire_out_of_band_sender_deserialize_impl(port_, oob_data)
    }

    #[no_mangle]
    pub extern "C" fn wire_out_of_band_sender_release(port_: i64, handle: u32) {
        wire_out_of_band_sender_release_impl(port_, handle)
    }

    // Section: allocate functions

    #[no_mangle]
    pub extern "C" fn new_uint_8_list_10(len: i32) -> *mut wire_uint_8_list {
        let ans = wire_uint_8_list {
            ptr: support::new_leak_vec_ptr(Default::default(), len),
            len,
        };
        support::new_leak_box_ptr(ans)
    }

    // Section: related functions

    // Section: impl Wire2Api

    impl Wire2Api<String> for *mut wire_uint_8_list {
        fn wire2api(self) -> String {
            let vec: Vec<u8> = self.wire2api();
            String::from_utf8_lossy(&vec).into_owned()
        }
    }

    impl Wire2Api<Vec<u8>> for *mut wire_uint_8_list {
        fn wire2api(self) -> Vec<u8> {
            unsafe {
                let wrap = support::box_from_leak_ptr(self);
                support::vec_from_leak_ptr(wrap.ptr, wrap.len)
            }
        }
    }
    // Section: wire structs

    #[repr(C)]
    #[derive(Clone)]
    pub struct wire_uint_8_list {
        ptr: *mut u8,
        len: i32,
    }

    // Section: impl NewWithNullPtr

    pub trait NewWithNullPtr {
        fn new_with_null_ptr() -> Self;
    }

    impl<T> NewWithNullPtr for *mut T {
        fn new_with_null_ptr() -> Self {
            std::ptr::null_mut()
        }
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;
