#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.67.0.

use crate::pool::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

// Section: wire functions

fn wire_open_main_pool_impl(
    port_: MessagePort,
    pool_config: impl Wire2Api<PoolConfig> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "open_main_pool",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_pool_config = pool_config.wire2api();
            move |task_callback| open_main_pool(api_pool_config)
        },
    )
}
fn wire_close_main_pool_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "close_main_pool",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| close_main_pool(),
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

// Section: impl IntoDart

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    use super::*;
    // Section: wire functions

    #[wasm_bindgen]
    pub fn wire_open_main_pool(port_: MessagePort, pool_config: JsValue) {
        wire_open_main_pool_impl(port_, pool_config)
    }

    #[wasm_bindgen]
    pub fn wire_close_main_pool(port_: MessagePort) {
        wire_close_main_pool_impl(port_)
    }

    // Section: allocate functions

    // Section: related functions

    // Section: impl Wire2Api

    impl Wire2Api<String> for String {
        fn wire2api(self) -> String {
            self
        }
    }

    impl Wire2Api<Option<String>> for Option<String> {
        fn wire2api(self) -> Option<String> {
            self.map(Wire2Api::wire2api)
        }
    }
    impl Wire2Api<PoolConfig> for JsValue {
        fn wire2api(self) -> PoolConfig {
            let self_ = self.dyn_into::<JsArray>().unwrap();
            assert_eq!(
                self_.length(),
                3,
                "Expected 3 elements, got {}",
                self_.length()
            );
            PoolConfig {
                genesis_path: self_.get(0).wire2api(),
                pool_name: self_.get(1).wire2api(),
                pool_config: self_.get(2).wire2api(),
            }
        }
    }

    impl Wire2Api<Vec<u8>> for Box<[u8]> {
        fn wire2api(self) -> Vec<u8> {
            self.into_vec()
        }
    }
    // Section: impl Wire2Api for JsValue

    impl Wire2Api<String> for JsValue {
        fn wire2api(self) -> String {
            self.as_string().expect("non-UTF-8 string, or not a string")
        }
    }
    impl Wire2Api<Option<String>> for JsValue {
        fn wire2api(self) -> Option<String> {
            (!self.is_undefined() && !self.is_null()).then(|| self.wire2api())
        }
    }
    impl Wire2Api<u8> for JsValue {
        fn wire2api(self) -> u8 {
            self.unchecked_into_f64() as _
        }
    }
    impl Wire2Api<Vec<u8>> for JsValue {
        fn wire2api(self) -> Vec<u8> {
            self.unchecked_into::<js_sys::Uint8Array>().to_vec().into()
        }
    }
}
#[cfg(target_family = "wasm")]
pub use web::*;

#[cfg(not(target_family = "wasm"))]
mod io {
    use super::*;
    // Section: wire functions

    #[no_mangle]
    pub extern "C" fn wire_open_main_pool(port_: i64, pool_config: *mut wire_PoolConfig) {
        wire_open_main_pool_impl(port_, pool_config)
    }

    #[no_mangle]
    pub extern "C" fn wire_close_main_pool(port_: i64) {
        wire_close_main_pool_impl(port_)
    }

    // Section: allocate functions

    #[no_mangle]
    pub extern "C" fn new_box_autoadd_pool_config_11() -> *mut wire_PoolConfig {
        support::new_leak_box_ptr(wire_PoolConfig::new_with_null_ptr())
    }

    #[no_mangle]
    pub extern "C" fn new_uint_8_list_11(len: i32) -> *mut wire_uint_8_list {
        let ans = wire_uint_8_list {
            ptr: support::new_leak_vec_ptr(Default::default(), len),
            len,
        };
        support::new_leak_box_ptr(ans)
    }

    // Section: related functions

    // Section: impl Wire2Api

    impl Wire2Api<String> for *mut wire_uint_8_list {
        fn wire2api(self) -> String {
            let vec: Vec<u8> = self.wire2api();
            String::from_utf8_lossy(&vec).into_owned()
        }
    }
    impl Wire2Api<PoolConfig> for *mut wire_PoolConfig {
        fn wire2api(self) -> PoolConfig {
            let wrap = unsafe { support::box_from_leak_ptr(self) };
            Wire2Api::<PoolConfig>::wire2api(*wrap).into()
        }
    }

    impl Wire2Api<PoolConfig> for wire_PoolConfig {
        fn wire2api(self) -> PoolConfig {
            PoolConfig {
                genesis_path: self.genesis_path.wire2api(),
                pool_name: self.pool_name.wire2api(),
                pool_config: self.pool_config.wire2api(),
            }
        }
    }

    impl Wire2Api<Vec<u8>> for *mut wire_uint_8_list {
        fn wire2api(self) -> Vec<u8> {
            unsafe {
                let wrap = support::box_from_leak_ptr(self);
                support::vec_from_leak_ptr(wrap.ptr, wrap.len)
            }
        }
    }
    // Section: wire structs

    #[repr(C)]
    #[derive(Clone)]
    pub struct wire_PoolConfig {
        genesis_path: *mut wire_uint_8_list,
        pool_name: *mut wire_uint_8_list,
        pool_config: *mut wire_uint_8_list,
    }

    #[repr(C)]
    #[derive(Clone)]
    pub struct wire_uint_8_list {
        ptr: *mut u8,
        len: i32,
    }

    // Section: impl NewWithNullPtr

    pub trait NewWithNullPtr {
        fn new_with_null_ptr() -> Self;
    }

    impl<T> NewWithNullPtr for *mut T {
        fn new_with_null_ptr() -> Self {
            std::ptr::null_mut()
        }
    }

    impl NewWithNullPtr for wire_PoolConfig {
        fn new_with_null_ptr() -> Self {
            Self {
                genesis_path: core::ptr::null_mut(),
                pool_name: core::ptr::null_mut(),
                pool_config: core::ptr::null_mut(),
            }
        }
    }

    impl Default for wire_PoolConfig {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;
